Tugas_1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import task_profile.urls as task_profile
import task_update.urls as task_update
import task_dashboard.urls as tugas_dashboard
import task_friend.urls as task_friend

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(task_profile, namespace='profile')),
    url(r'^update_status/', include(task_update, namespace='update_status')),
    url(r'^dashboard/', include(tugas_dashboard, namespace='dashboard')),
    url(r'^friend/', include(task_friend, namespace='friend')),
    url(r'^$', RedirectView.as_view(permanent = True, url='/update_status/'), name='index'),
]

task_dashboard/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

task_friend/urls.py
from django.conf.urls import url
from .views import index, add_friend

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friend', add_friend, name='add_friend'),
]

task_profile/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

task_update/urls.py
from django.conf.urls import url
from .views import index, add_status, delete_status

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_status', add_status, name='add_status'),
	url(r'^delete/(?P<pk>\d+)/$', delete_status, name='delete_status')
]

task_dashboard/models.py
from django.db import models

# Create your models here.

task_friend/models.py
from django.db import models

class Friends(models.Model):
	name = models.CharField(max_length=30)
	url = models.URLField(max_length=200)
	date = models.DateTimeField(auto_now_add=True)

task_profile/models.py
from django.db import models

# Create your models here.

class Profile(models.Model):
	u_name = models.CharField(max_length=50)
	gender = models.CharField(max_length=6)
	desc = models.TextField(max_length=350)
	email = models.EmailField()

class Expertise(models.Model):
	exp = models.TextField(max_length=100)

task_update/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    status = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
    	ordering = ('status', 'created_date')

task_friend/forms.py
from django import forms

class Friend_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan URL',
    }
    name_attrs = {
        'class': 'form-control',
        'placeholder': "Your friend's name",
    }
    url_attrs = {
        'class': 'form-control',
        'placeholder': "Your friend's herokuapp",
    }

    name = forms.CharField(label="Name",required=True, max_length=27, widget=forms.TextInput(attrs=name_attrs))
    url = forms.URLField(label="Url",required=True, widget=forms.URLInput(attrs=url_attrs))

task_update/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Please, fill this',
    }
    status_attrs = {
        'type': 'text',
        'cols': 150,
        'rows': 4,
        'class': 'status-form-textarea',
        'placeholder':'What do u feel, now?'
    }

    status = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=status_attrs))

task_dashboard/views.py
from django.shortcuts import render
from task_friend.models import Friends
from task_update.models import Status
# Create your views here.
response= {}
def index(request):
	response['title'] = 'Statistic'
	html = 'task_dashboard/task_dashboard.html'
	response['friends_count'] = Friends.objects.count()
	response['feed_count'] = Status.objects.count()
	if (Status.objects.count() > 0):
		response['latest_post'] = Status.objects.last()
	response['author'] = 'Windi Chandra'
	return render(request, html, response)

task_friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Friend_Form
from .models import Friends
from django.contrib import messages
import urllib

response = {}
def index(request):
    html = 'task_friend/task_friend.html'
    response['author'] = 'Izzatul Muttaqin'
    response['title'] = 'Friend'
    response['form'] = Friend_Form
    friends = Friends.objects.all()
    response['friend'] = friends

    return render(request, html, response)

def add_friend(request):
    form = Friend_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid() and '.herokuapp.com' in request.POST['url']):
        try:
            code = urllib.request.urlopen(request.POST['url']).getcode()
            response['name'] = request.POST['name']
            response['url'] = request.POST['url']
            friend = Friends(name=response['name'], url=response['url'])
            friend.save()
            return HttpResponseRedirect('/friend/')
        except:
            messages.warning(request, 'Please insert a valid herokuapp.')
            return HttpResponseRedirect('/friend/')
    else:
        messages.warning(request, 'Please input herokuapp site.')
        return HttpResponseRedirect('/friend/')

task_profile/views.py
from django.shortcuts import render
from datetime import datetime, date
from .models import Profile, Expertise

# Create your views here.
u_name = 'Ariana Grande'
gender ='Female'
desc = 'PPW is my favorite subject no matter how hard TDD is. *currently crying*'
email = 'holla@gmail.com'
birthdate = date(1995, 10, 31)
birth_date = birthdate.strftime('%d %B')
exp = ['Django', 'Tapi Boong']

#bio_dict = [{'subject' : 'Birthday', 'value' : birth_date},\
#{'subject' : 'Gender', 'value' : gender}, \
#{'subject' : 'Description', 'value' : desc}, {'subject' : 'Email', 'value' : email}]

def index(request):
	profile = Profile(u_name=u_name, gender=gender, desc=desc, email=email)
	expert = Expertise(exp=exp)
	response = {'u_name' : profile.u_name, 'birth_date' : birth_date, \
	'gender':profile.gender, 'desc':profile.desc, 'email':profile.email, 'exp' : expert.exp}
	response['author'] = 'Fannyah Dita'
	response['title'] = 'Profile'
	html = 'tugas_profile/tugas_profile.html'
	return render(request, html, response)

task_update/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status

name='Ariana Grande'
gender='female'
email='holla@gmail.com'
author='group 15'


# Create your views here.
response = {}

def index(request):
    response['author'] = 'Rachel Sausan'
    response['title'] = 'Status'
    response['name'] = author #TODO Implement yourname
    status = Status.objects.all().order_by('-created_date')
    response['database'] = status
    html = 'task_update/update_status.html'
    response['status_form'] = Status_Form
    response['profile_name'] = name
    return render(request, html, response)

def add_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['status'] = request.POST['status']
        status = Status(status=response['status'])
        status.save()
        return HttpResponseRedirect('/update_status/')
    else:
        return HttpResponseRedirect('/update_status/')

def delete_status(request, pk):
    status = Status.objects.filter(pk=pk).first()
    if status != None:
        status.delete()
        pass
    return HttpResponseRedirect('/update_status/')

task_dashboard/templates/task_dashboard/task_dashboard.html
{% extends "base.html" %}

{% block content %}

{% load staticfiles %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/task_dashboard.css' %}">
<div class="container">
    <h1 style="text-align: center;">Ariana Grande</h1>

    <div class="col-sm-6" >
        <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
        Feed : {{ feed_count }}
    </div>
    <div class="col-sm-6" >
        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
        Friends : {{ friends_count }}
    </div>
    <div class="" style="padding: 30px;font-size: 25px;">
        Latest Post<br>
        {% if latest_post %}
        <img src="https://thumb.ibb.co/iUaq5b/if_arrow138_216456.png" width="100" height="100" style="padding: 20px;" class="img-circle"> Ariana Grande <br>
        <h2 class="status">{{ latest_post.status }}</h2>
        <h6 class="tanggal">{{ latest_post.created_date }}</h6>
        {% else %}
        <p>No post yet</p>
        {% endif %}
    </div>
</div>
{% endblock %}

task_friend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    

    <title> 
        Ling In - {{ title }}
    </title>
</head>
<style type="text/css">
    body{
        background: #80A6C3;
    }
    h2, button{
        font-family: 'Quicksand';
    }
    h1{
        text-transform: uppercase;
        font-family: 'Quicksand';
    }
    a, footer{
        font-family: 'Quicksand';
        font-size: 20px;
    }
</style>

<body>
    <header>
        <!-- templates/lab_5/partials/header.html -->
        <nav class="navbar navbar-default">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="">Ling In</a>
            </div>
            
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-right">
                <!-- LINK MENUJU table, dan link menuju home#form -->
                <li><a href="/update_status/">Status</a> </li>
                <li><a href="/profile/">Profile</a></li>
                <li><a href="/friend/">Friends</a> </li>
                <li><a href="/dashboard/">Stats</a> </li>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </nav>
    </header>

    <content>
        {% block content %}
                <!-- content goes here -->
        {% endblock %}
    <content>

    <footer>
        <p align="center">&copy; Created by {{ author }}</p>
    </footer>
    
    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

task_friend/templates/task_friend/task_friend.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/task_friend.css' %}">

<h1 style="text-align:center;" class="jarak">Friend</h1>

<section name="form" style="background:lightgrey;" class="jarak">
    <div class="container">
    <h2>Add Friends</h2>
    <form id="form" method="POST" action="{% url 'friend:add_friend' %}">
        
        {% csrf_token %}
        
            <div class="row">
            {% for field in form  %}
              <div class="col-sm-1">
                {{ field.label_tag }}
              </div>
              <div class="col-sm-11">
                {{ field }} 
              </div>
            {% endfor %}
            </div>
        
        <button type="submit" class="btn btn-lg btn-default pull-right">Submit</button>
    </form>
    </div>
    
    {% if messages %}
    <br>
    <div class="alert alert-danger text-center jarak">
      <ul class="messages">
        {% for message in messages %}
          <div>{{ message }}</div>
        {% endfor %}
      </ul>
    </div>
    {% endif %}

</section>

<br>
<br>

<section name="my-list" id="my-list">
    <div class="container">
        <h2>List Friends</h2>

            <div class="flex">
                {% if friend %}
                    {% for data in friend %}
                        <div class="flex-item">
                            <div class="to-do-list">
                                <div class="to-do-list-title">
                                    {{data.name}}
                                </div>
                                <div class="to-do-list-date-added">
                                    {{data.date}}
                                </div>
                                <div class="to-do-list-description">
                                    <img height="105" witdh="105" class="img-circle" src="http://www.colorado.edu/biofrontiers/sites/default/files/styles/small/public/people/cassidythompson.png?itok=2Cx5T92l" align="center">
                                </div>
                                <div class="to-do-list-delete">
                                    <div class="to-do-list-delete-button"><a href={{data.url}}>{{data.url}}</a></div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                <div class="alert alert-danger text-center">
                    <strong>Oops!</strong> Tidak ada data Todo.
                </div>
                {% endif %}
            </div>
        
    </div>
</section>

<hr/>

{% endblock %}

task_profile/templates/tugas_profile/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
  	<meta name="description" content="Profile Page">
  	<meta name="author" content="Fannyah Dita">
 	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
	<title>{{ u_name }}</title>
</head>
<style>
	h1{
		text-align: center;
		font-family: 'Quicksand';
		font-size: 50px;
		padding: 20px;
	}
	td {
		padding-right: 20px;
		padding-left: 10px;
		padding-bottom: 5px;
		text-align: center;
	}
	table {
		font-family: 'Quicksand';
		margin-top: 20px;
		margin-left: 500px;
	}

	img{
		position: absolute;
		top: 100px;
		left: 50%;
		transform: translateX(-50%);
		border-radius: 50%;
	}
	h2{
		font-family: 'Quicksand';
		font-size: 40px;
		margin-top: 310px;
	}

</style>
<body style="background-color: white">
	<content>
		{% block content %}
		{% endblock %}
	</content>
</body>

task_profile/templates/tugas_profile/tugas_profile.html
{% extends "base.html" %}

{% block content %}

{% load staticfiles %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/tugas_profile.css' %}">

<h1 class="main-title">PROFILE</h1>
<p>
	<img class="img-circle" src="http://78.media.tumblr.com/696e677b7638ed105f875c36b737b16d/tumblr_o1bfnuUfQp1tg72yro1_250.gif" align="center">
</p>
<h2 class="username">{{ u_name }}</h2>

<hr>

<table class="tabel-profile" align="center" width="400" cellpadding="40" cellspacing="20">
        <tr>
            <td class="subject">Birthdate</td>
            <td class="value">{{ birth_date }}</td>
        </tr>
        <tr>
            <td class="subject">Gender</td>
            <td class="value">{{ gender }}</td>
        </tr>
    	<tr>
    		<td class="subject">Expertise</td> 
    		<td class="val-exp">{% for ii in exp %}<span class="expertise">{{ ii }}</span>{% endfor %}
            </td> 
        </tr>
        <tr>
            <td class="subject">Description</td>
            <td class="value">{{ desc }}</td>
        </tr>
        <tr>
            <td class="subject">Email</td>
            <td class="value">{{ email }}</td>
        </tr>
</table>
<hr/>
{% endblock %}

task_update/templates/task_update/update_status.html
{% extends "base.html" %}

{% block content %}

{% load staticfiles %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/update_status.css' %}">
<section name="input-list" id="input-list">
       <form id="form" method="POST" action="{% url 'update_status:add_status' %}">
        <h1><img class = "img-circle" src="http://78.media.tumblr.com/696e677b7638ed105f875c36b737b16d/tumblr_o1bfnuUfQp1tg72yro1_250.gif" style="float:left;" width="50px" height="50px" alt="my-photo" />     Update Status</h1>
            {% csrf_token %}
            {{ status_form }}
            <input id="submit" type="submit" class="btn btn-lg btn-block" value="Post">
            <br>
        </form>
    </section>

        <h1 class="title">Your Status</h1>
    <section name="my-list" id="my-list">
        <div class="flex">
            {% if database %}
                {% for data in database %}
                    <div class="flex-item">
                        <h3 color = "yellow"><img class = "img-circle" src="http://78.media.tumblr.com/696e677b7638ed105f875c36b737b16d/tumblr_o1bfnuUfQp1tg72yro1_250.gif" style="float:left;" width="35px" height="35px" alt="my-photo" />    {{profile_name}}</h3>
                            <div class="status-message">
                                {{data.status}}
                            </div>
                            <div class="status-date-added">
                                {{data.created_date}}
                            </div>
                            <div class="to-do-list-description">
                                {{data.description}}
                            </div>
                            <div class="to-do-list-delete">
                                <div class="to-do-list-delete-button" data-id="{{data.id}}">Delete</div>
                            </div>
                        </div>       
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data Status.
            </div>
            {% endif %}
        </div>
    </section>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="application/javascript">
    $(function() {
        $('.to-do-list-delete-button').click(function() {
            var id = $(this).data('id')
            location.href = "/update_status/delete/" + id + "/"
        });
    });
</script>
</div>

<hr/>

{% endblock %}  

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    
    <link rel="icon" type="image/png" size="16x16" href="https://thumb.ibb.co/iUaq5b/if_arrow138_216456.png">
    <title> 
        Ling In - {{ title }}
    </title>
</head>
<style type="text/css">
    body{
        background: #80A6C3;
    }
    h2, button{
        font-family: 'Quicksand';
    }
    h1{
        text-transform: uppercase;
        font-family: 'Quicksand';
    }
    a{
        font-family: 'Quicksand';
        font-size: 22px;
    }
    footer{
        padding-top: 0px;
        margin: auto;
        padding-bottom: 0px;
        font-family: 'Quicksand'
        font-size: 14px;
    }
</style>

<body>
    <header>
        <!-- templates/lab_5/partials/header.html -->
        <nav class="navbar navbar-default navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            <a class="navbar-brand" href="" style="font-family: 'Nanoto', sans-serif; font-size: 27px;">Ling In
                    <img src="https://thumb.ibb.co/iUaq5b/if_arrow138_216456.png" alt="if_arrow138_216456" border="0" width="20" height="30">
                    <img src="https://thumb.ibb.co/iUaq5b/if_arrow138_216456.png" alt="if_arrow138_216456" border="0" width="20" height="30">
              </a>
            </div>

            
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-right">
                <!-- LINK MENUJU table, dan link menuju home#form -->
                <li><a href="/update_status/">Status</a></li>
                <li><a href="/profile/">Profile</a></li>
                <li><a href="/friend/">Friends</a> </li>
                <li><a href="/dashboard/">Stats</a> </li>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </nav>
    </header>

    <content>
        {% block content %}
                <!-- content goes here -->
        {% endblock %}
    <content>

    <footer>
        <p align="center">&copy; Created by {{ author }}</p>
    </footer>
    
    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>